sudo: required
services:
  - docker

before_install:
  - docker build -t gvickyin/firstdockerapp -f Dockerfile.dev .

script:
  - docker run gvickyin/firstdockerapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "firstdockerapp"
  env: "Firstdockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-987608871076"
  bucket_path: "firstdockerapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"